module.exports = {
  DATABASE: process.env.MONGO_URI,
  SESSION_SECRET: process.env.SESSION_SECRET,
  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET
};
